"use client";

import { useEffect, useState, useRef } from "react";
import {
  useAccount,
  useWriteContract,
  useWaitForTransactionReceipt,
} from "wagmi";
import { TrafficLogABI } from "@/contracts/abis";
import { contractAddresses } from "@/contracts/addresses";
import { uploadJSONToIPFS } from "@/utils/pinata";
import { trafficCongestionData } from "./CityVehicles";

// Auto-logger component for traffic congestion
export function TrafficCongestionMonitor() {
  const { address, isConnected } = useAccount();
  const { writeContract, data: hash } = useWriteContract();
  const { isSuccess } = useWaitForTransactionReceipt({ hash });

  const [lastLogTime, setLastLogTime] = useState(0);
  const [isLogging, setIsLogging] = useState(false);
  const congestionCheckInterval = useRef<NodeJS.Timeout | null>(null);

  // Monitor congestion and auto-log to blockchain
  useEffect(() => {
    if (!isConnected || !address) {
      console.log("🚦 Monitor: Not connected or no address");
      return;
    }

    congestionCheckInterval.current = setInterval(async () => {
      const now = Date.now();
      const timeSinceLastLog = now - lastLogTime;

      // Debug logging
      console.log("🚦 Congestion check:", {
        congestionLevel: trafficCongestionData.congestionLevel,
        threshold: 70,
        timeSinceLastLog: timeSinceLastLog / 1000 + "s",
        isLogging,
        stoppedVehicles: trafficCongestionData.stoppedVehicles,
        totalVehicles: trafficCongestionData.totalVehicles,
      });

      // Only log if:
      // 1. Congestion is high (>70%)
      // 2. At least 30 seconds since last log (to avoid spam)
      // 3. Not currently logging
      if (
        trafficCongestionData.congestionLevel > 70 &&
        timeSinceLastLog > 30000 &&
        !isLogging
      ) {
        console.log("🚦 CONDITIONS MET - Starting auto-log process...");
        try {
          setIsLogging(true);

          // Prepare detailed congestion data for IPFS
          const congestionReport = {
            timestamp: now,
            metrics: {
              totalVehicles: trafficCongestionData.totalVehicles,
              stoppedVehicles: trafficCongestionData.stoppedVehicles,
              averageSpeed: trafficCongestionData.averageSpeed,
              congestionLevel: trafficCongestionData.congestionLevel,
            },
            location: "NeoCity 3D Real-time Simulation",
            affectedAreas: [
              "Main Intersection (0, 0)",
              "Secondary Intersections",
            ],
            aiPrediction: {
              estimatedDuration: Math.floor(Math.random() * 30) + 15, // 15-45 mins
              recommendedAction: "Signal timing adjustment recommended",
              alternativeRoutes: [
                "Route via East corridor",
                "Route via West bypass",
              ],
            },
            autoGenerated: true,
          };

          // Upload to IPFS
          const ipfsHash = await uploadJSONToIPFS(congestionReport, {
            name: `traffic-congestion-auto-${now}`,
            keyvalues: {
              type: "auto-traffic-log",
              congestionLevel: trafficCongestionData.congestionLevel.toString(),
              timestamp: now.toString(),
              source: "3D-simulation",
            },
          });

          console.log("🚦 IPFS upload successful:", ipfsHash);

          // Determine congestion level enum (0=Low, 1=Medium, 2=High, 3=Critical)
          let congestionLevelEnum = 1; // Medium
          if (trafficCongestionData.congestionLevel > 90) {
            congestionLevelEnum = 3; // Critical
          } else if (trafficCongestionData.congestionLevel > 70) {
            congestionLevelEnum = 2; // High
          }

          // Log to blockchain
          writeContract({
            address: contractAddresses.TrafficLog as `0x${string}`,
            abi: TrafficLogABI,
            functionName: "logTrafficData",
            args: [
              "NeoCity 3D Simulation - High Congestion Detected",
              congestionLevelEnum,
              1, // ActionType: SignalAdjustment
              `Auto-detected: ${trafficCongestionData.stoppedVehicles}/${
                trafficCongestionData.totalVehicles
              } vehicles stopped. Congestion level: ${trafficCongestionData.congestionLevel.toFixed(
                1
              )}%`,
              ipfsHash,
              false, // Not emergency
            ],
          });

          console.log("🚦 Blockchain transaction initiated");

          setLastLogTime(now);
          console.log("🚦 Auto-logged traffic congestion to blockchain:", {
            congestionLevel: trafficCongestionData.congestionLevel,
            ipfsHash,
            hash,
          });
        } catch (error) {
          console.error("❌ Failed to auto-log traffic congestion:", error);
          setIsLogging(false); // Reset on error
        } finally {
          // Don't reset isLogging here - wait for transaction success
        }
      }
    }, 5000); // Check every 5 seconds

    return () => {
      if (congestionCheckInterval.current) {
        clearInterval(congestionCheckInterval.current);
      }
    };
  }, [isConnected, address, lastLogTime, isLogging, writeContract, hash]);

  // Reset logging flag on success
  useEffect(() => {
    if (isSuccess) {
      setIsLogging(false);
    }
  }, [isSuccess]);

  // Visual indicator (optional - shows when auto-logging is active)
  if (!isConnected || trafficCongestionData.congestionLevel <= 70) return null;

  return (
    <div className="fixed bottom-4 right-4 z-50 pointer-events-none">
      <div className="bg-red-500/90 backdrop-blur-sm border-2 border-red-400 rounded-xl px-4 py-3 shadow-2xl">
        <div className="flex items-center gap-3">
          <div className="relative">
            <div className="w-3 h-3 bg-red-400 rounded-full animate-ping absolute"></div>
            <div className="w-3 h-3 bg-red-600 rounded-full"></div>
          </div>
          <div>
            <p className="text-white font-semibold text-sm">
              High Traffic Congestion Detected
            </p>
            <p className="text-red-100 text-xs">
              {trafficCongestionData.congestionLevel.toFixed(0)}% congestion -
              Auto-logging to blockchain
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
